// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module top_ntt_ntt_core (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        buf_r_address0,
        buf_r_ce0,
        buf_r_q0,
        buf_r_address1,
        buf_r_ce1,
        buf_r_we1,
        buf_r_d1,
        zbuf_address0,
        zbuf_ce0,
        zbuf_q0
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] buf_r_address0;
output   buf_r_ce0;
input  [31:0] buf_r_q0;
output  [7:0] buf_r_address1;
output   buf_r_ce1;
output   buf_r_we1;
output  [31:0] buf_r_d1;
output  [7:0] zbuf_address0;
output   zbuf_ce0;
input  [31:0] zbuf_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [7:0] len_3_reg_189;
wire    ap_CS_fsm_state2;
wire   [10:0] zext_ln21_fu_102_p1;
reg   [10:0] zext_ln21_reg_197;
wire   [7:0] trunc_ln27_fu_114_p1;
reg   [7:0] trunc_ln27_reg_202;
wire   [63:0] zext_ln27_fu_118_p1;
reg   [63:0] zext_ln27_reg_207;
wire   [7:0] trunc_ln20_fu_138_p1;
reg   [7:0] trunc_ln20_reg_215;
wire    ap_CS_fsm_state3;
wire   [63:0] add_ln27_fu_142_p2;
reg   [63:0] add_ln27_reg_220;
wire    grp_ntt_core_Pipeline_BUTTER_fu_69_ap_start;
wire    grp_ntt_core_Pipeline_BUTTER_fu_69_ap_done;
wire    grp_ntt_core_Pipeline_BUTTER_fu_69_ap_idle;
wire    grp_ntt_core_Pipeline_BUTTER_fu_69_ap_ready;
wire   [7:0] grp_ntt_core_Pipeline_BUTTER_fu_69_buf_r_address0;
wire    grp_ntt_core_Pipeline_BUTTER_fu_69_buf_r_ce0;
wire   [7:0] grp_ntt_core_Pipeline_BUTTER_fu_69_buf_r_address1;
wire    grp_ntt_core_Pipeline_BUTTER_fu_69_buf_r_ce1;
wire    grp_ntt_core_Pipeline_BUTTER_fu_69_buf_r_we1;
wire   [31:0] grp_ntt_core_Pipeline_BUTTER_fu_69_buf_r_d1;
wire   [7:0] grp_ntt_core_Pipeline_BUTTER_fu_69_zbuf_address0;
wire    grp_ntt_core_Pipeline_BUTTER_fu_69_zbuf_ce0;
reg   [63:0] start_reg_58;
wire    ap_CS_fsm_state5;
wire   [0:0] icmp_ln24_fu_96_p2;
reg    grp_ntt_core_Pipeline_BUTTER_fu_69_ap_start_reg;
wire    ap_CS_fsm_state4;
reg   [10:0] k_fu_50;
wire   [10:0] k_1_fu_147_p2;
wire   [0:0] icmp_ln27_fu_132_p2;
reg   [7:0] len_fu_54;
wire   [7:0] zext_ln24_fu_161_p1;
wire   [8:0] mul_fu_106_p3;
wire   [55:0] tmp_fu_122_p4;
wire   [6:0] len_1_fu_152_p4;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 grp_ntt_core_Pipeline_BUTTER_fu_69_ap_start_reg = 1'b0;
#0 k_fu_50 = 11'd0;
#0 len_fu_54 = 8'd0;
end

top_ntt_ntt_core_Pipeline_BUTTER grp_ntt_core_Pipeline_BUTTER_fu_69(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ntt_core_Pipeline_BUTTER_fu_69_ap_start),
    .ap_done(grp_ntt_core_Pipeline_BUTTER_fu_69_ap_done),
    .ap_idle(grp_ntt_core_Pipeline_BUTTER_fu_69_ap_idle),
    .ap_ready(grp_ntt_core_Pipeline_BUTTER_fu_69_ap_ready),
    .len(len_3_reg_189),
    .empty_16(trunc_ln20_reg_215),
    .empty(trunc_ln27_reg_202),
    .buf_r_address0(grp_ntt_core_Pipeline_BUTTER_fu_69_buf_r_address0),
    .buf_r_ce0(grp_ntt_core_Pipeline_BUTTER_fu_69_buf_r_ce0),
    .buf_r_q0(buf_r_q0),
    .buf_r_address1(grp_ntt_core_Pipeline_BUTTER_fu_69_buf_r_address1),
    .buf_r_ce1(grp_ntt_core_Pipeline_BUTTER_fu_69_buf_r_ce1),
    .buf_r_we1(grp_ntt_core_Pipeline_BUTTER_fu_69_buf_r_we1),
    .buf_r_d1(grp_ntt_core_Pipeline_BUTTER_fu_69_buf_r_d1),
    .zbuf_address0(grp_ntt_core_Pipeline_BUTTER_fu_69_zbuf_address0),
    .zbuf_ce0(grp_ntt_core_Pipeline_BUTTER_fu_69_zbuf_ce0),
    .zbuf_q0(zbuf_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ntt_core_Pipeline_BUTTER_fu_69_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_ntt_core_Pipeline_BUTTER_fu_69_ap_start_reg <= 1'b1;
        end else if ((grp_ntt_core_Pipeline_BUTTER_fu_69_ap_ready == 1'b1)) begin
            grp_ntt_core_Pipeline_BUTTER_fu_69_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        k_fu_50 <= 11'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln27_fu_132_p2 == 1'd0))) begin
        k_fu_50 <= k_1_fu_147_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        len_fu_54 <= 8'd128;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln27_fu_132_p2 == 1'd0))) begin
        len_fu_54 <= zext_ln24_fu_161_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln24_fu_96_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        start_reg_58 <= 64'd0;
    end else if (((grp_ntt_core_Pipeline_BUTTER_fu_69_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        start_reg_58 <= add_ln27_reg_220;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln27_reg_220 <= add_ln27_fu_142_p2;
        trunc_ln20_reg_215 <= trunc_ln20_fu_138_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        len_3_reg_189 <= len_fu_54;
        trunc_ln27_reg_202 <= trunc_ln27_fu_114_p1;
        zext_ln21_reg_197[7 : 0] <= zext_ln21_fu_102_p1[7 : 0];
        zext_ln27_reg_207[8 : 1] <= zext_ln27_fu_118_p1[8 : 1];
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_ntt_core_Pipeline_BUTTER_fu_69_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)) | ((icmp_ln24_fu_96_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln24_fu_96_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln24_fu_96_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln27_fu_132_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_ntt_core_Pipeline_BUTTER_fu_69_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln27_fu_142_p2 = (zext_ln27_reg_207 + start_reg_58);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign buf_r_address0 = grp_ntt_core_Pipeline_BUTTER_fu_69_buf_r_address0;

assign buf_r_address1 = grp_ntt_core_Pipeline_BUTTER_fu_69_buf_r_address1;

assign buf_r_ce0 = grp_ntt_core_Pipeline_BUTTER_fu_69_buf_r_ce0;

assign buf_r_ce1 = grp_ntt_core_Pipeline_BUTTER_fu_69_buf_r_ce1;

assign buf_r_d1 = grp_ntt_core_Pipeline_BUTTER_fu_69_buf_r_d1;

assign buf_r_we1 = grp_ntt_core_Pipeline_BUTTER_fu_69_buf_r_we1;

assign grp_ntt_core_Pipeline_BUTTER_fu_69_ap_start = grp_ntt_core_Pipeline_BUTTER_fu_69_ap_start_reg;

assign icmp_ln24_fu_96_p2 = ((len_fu_54 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln27_fu_132_p2 = (($signed(tmp_fu_122_p4) < $signed(56'd1)) ? 1'b1 : 1'b0);

assign k_1_fu_147_p2 = (zext_ln21_reg_197 + k_fu_50);

assign len_1_fu_152_p4 = {{len_fu_54[7:1]}};

assign mul_fu_106_p3 = {{len_fu_54}, {1'd0}};

assign tmp_fu_122_p4 = {{start_reg_58[63:8]}};

assign trunc_ln20_fu_138_p1 = start_reg_58[7:0];

assign trunc_ln27_fu_114_p1 = k_fu_50[7:0];

assign zbuf_address0 = grp_ntt_core_Pipeline_BUTTER_fu_69_zbuf_address0;

assign zbuf_ce0 = grp_ntt_core_Pipeline_BUTTER_fu_69_zbuf_ce0;

assign zext_ln21_fu_102_p1 = len_fu_54;

assign zext_ln24_fu_161_p1 = len_1_fu_152_p4;

assign zext_ln27_fu_118_p1 = mul_fu_106_p3;

always @ (posedge ap_clk) begin
    zext_ln21_reg_197[10:8] <= 3'b000;
    zext_ln27_reg_207[0] <= 1'b0;
    zext_ln27_reg_207[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
end

endmodule //top_ntt_ntt_core
