-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity top_ntt_ntt_core is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    buf_r_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    buf_r_ce0 : OUT STD_LOGIC;
    buf_r_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    buf_r_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    buf_r_ce1 : OUT STD_LOGIC;
    buf_r_we1 : OUT STD_LOGIC;
    buf_r_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    zbuf_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    zbuf_ce0 : OUT STD_LOGIC;
    zbuf_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of top_ntt_ntt_core is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv56_1 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal len_3_reg_189 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal zext_ln21_fu_102_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln21_reg_197 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln27_fu_114_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln27_reg_202 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln27_fu_118_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln27_reg_207 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln20_fu_138_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln20_reg_215 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal add_ln27_fu_142_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln27_reg_220 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_ntt_core_Pipeline_BUTTER_fu_69_ap_start : STD_LOGIC;
    signal grp_ntt_core_Pipeline_BUTTER_fu_69_ap_done : STD_LOGIC;
    signal grp_ntt_core_Pipeline_BUTTER_fu_69_ap_idle : STD_LOGIC;
    signal grp_ntt_core_Pipeline_BUTTER_fu_69_ap_ready : STD_LOGIC;
    signal grp_ntt_core_Pipeline_BUTTER_fu_69_buf_r_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_ntt_core_Pipeline_BUTTER_fu_69_buf_r_ce0 : STD_LOGIC;
    signal grp_ntt_core_Pipeline_BUTTER_fu_69_buf_r_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_ntt_core_Pipeline_BUTTER_fu_69_buf_r_ce1 : STD_LOGIC;
    signal grp_ntt_core_Pipeline_BUTTER_fu_69_buf_r_we1 : STD_LOGIC;
    signal grp_ntt_core_Pipeline_BUTTER_fu_69_buf_r_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_ntt_core_Pipeline_BUTTER_fu_69_zbuf_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_ntt_core_Pipeline_BUTTER_fu_69_zbuf_ce0 : STD_LOGIC;
    signal start_reg_58 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal icmp_ln24_fu_96_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_ntt_core_Pipeline_BUTTER_fu_69_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal k_fu_50 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal k_1_fu_147_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln27_fu_132_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal len_fu_54 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal zext_ln24_fu_161_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_fu_106_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_fu_122_p4 : STD_LOGIC_VECTOR (55 downto 0);
    signal len_1_fu_152_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component top_ntt_ntt_core_Pipeline_BUTTER IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        len : IN STD_LOGIC_VECTOR (7 downto 0);
        empty_16 : IN STD_LOGIC_VECTOR (7 downto 0);
        empty : IN STD_LOGIC_VECTOR (7 downto 0);
        buf_r_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        buf_r_ce0 : OUT STD_LOGIC;
        buf_r_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        buf_r_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        buf_r_ce1 : OUT STD_LOGIC;
        buf_r_we1 : OUT STD_LOGIC;
        buf_r_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        zbuf_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        zbuf_ce0 : OUT STD_LOGIC;
        zbuf_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    grp_ntt_core_Pipeline_BUTTER_fu_69 : component top_ntt_ntt_core_Pipeline_BUTTER
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_ntt_core_Pipeline_BUTTER_fu_69_ap_start,
        ap_done => grp_ntt_core_Pipeline_BUTTER_fu_69_ap_done,
        ap_idle => grp_ntt_core_Pipeline_BUTTER_fu_69_ap_idle,
        ap_ready => grp_ntt_core_Pipeline_BUTTER_fu_69_ap_ready,
        len => len_3_reg_189,
        empty_16 => trunc_ln20_reg_215,
        empty => trunc_ln27_reg_202,
        buf_r_address0 => grp_ntt_core_Pipeline_BUTTER_fu_69_buf_r_address0,
        buf_r_ce0 => grp_ntt_core_Pipeline_BUTTER_fu_69_buf_r_ce0,
        buf_r_q0 => buf_r_q0,
        buf_r_address1 => grp_ntt_core_Pipeline_BUTTER_fu_69_buf_r_address1,
        buf_r_ce1 => grp_ntt_core_Pipeline_BUTTER_fu_69_buf_r_ce1,
        buf_r_we1 => grp_ntt_core_Pipeline_BUTTER_fu_69_buf_r_we1,
        buf_r_d1 => grp_ntt_core_Pipeline_BUTTER_fu_69_buf_r_d1,
        zbuf_address0 => grp_ntt_core_Pipeline_BUTTER_fu_69_zbuf_address0,
        zbuf_ce0 => grp_ntt_core_Pipeline_BUTTER_fu_69_zbuf_ce0,
        zbuf_q0 => zbuf_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_ntt_core_Pipeline_BUTTER_fu_69_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_ntt_core_Pipeline_BUTTER_fu_69_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_ntt_core_Pipeline_BUTTER_fu_69_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_ntt_core_Pipeline_BUTTER_fu_69_ap_ready = ap_const_logic_1)) then 
                    grp_ntt_core_Pipeline_BUTTER_fu_69_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    k_fu_50_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                k_fu_50 <= ap_const_lv11_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln27_fu_132_p2 = ap_const_lv1_0))) then 
                k_fu_50 <= k_1_fu_147_p2;
            end if; 
        end if;
    end process;

    len_fu_54_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                len_fu_54 <= ap_const_lv8_80;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln27_fu_132_p2 = ap_const_lv1_0))) then 
                len_fu_54 <= zext_ln24_fu_161_p1;
            end if; 
        end if;
    end process;

    start_reg_58_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln24_fu_96_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                start_reg_58 <= ap_const_lv64_0;
            elsif (((grp_ntt_core_Pipeline_BUTTER_fu_69_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                start_reg_58 <= add_ln27_reg_220;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                add_ln27_reg_220 <= add_ln27_fu_142_p2;
                trunc_ln20_reg_215 <= trunc_ln20_fu_138_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                len_3_reg_189 <= len_fu_54;
                trunc_ln27_reg_202 <= trunc_ln27_fu_114_p1;
                    zext_ln21_reg_197(7 downto 0) <= zext_ln21_fu_102_p1(7 downto 0);
                    zext_ln27_reg_207(8 downto 1) <= zext_ln27_fu_118_p1(8 downto 1);
            end if;
        end if;
    end process;
    zext_ln21_reg_197(10 downto 8) <= "000";
    zext_ln27_reg_207(0) <= '0';
    zext_ln27_reg_207(63 downto 9) <= "0000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, grp_ntt_core_Pipeline_BUTTER_fu_69_ap_done, ap_CS_fsm_state5, icmp_ln24_fu_96_p2, icmp_ln27_fu_132_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln24_fu_96_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln27_fu_132_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((grp_ntt_core_Pipeline_BUTTER_fu_69_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    add_ln27_fu_142_p2 <= std_logic_vector(unsigned(zext_ln27_reg_207) + unsigned(start_reg_58));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_ntt_core_Pipeline_BUTTER_fu_69_ap_done)
    begin
        if ((grp_ntt_core_Pipeline_BUTTER_fu_69_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln24_fu_96_p2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)) or ((icmp_ln24_fu_96_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln24_fu_96_p2)
    begin
        if (((icmp_ln24_fu_96_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    buf_r_address0 <= grp_ntt_core_Pipeline_BUTTER_fu_69_buf_r_address0;
    buf_r_address1 <= grp_ntt_core_Pipeline_BUTTER_fu_69_buf_r_address1;
    buf_r_ce0 <= grp_ntt_core_Pipeline_BUTTER_fu_69_buf_r_ce0;
    buf_r_ce1 <= grp_ntt_core_Pipeline_BUTTER_fu_69_buf_r_ce1;
    buf_r_d1 <= grp_ntt_core_Pipeline_BUTTER_fu_69_buf_r_d1;
    buf_r_we1 <= grp_ntt_core_Pipeline_BUTTER_fu_69_buf_r_we1;
    grp_ntt_core_Pipeline_BUTTER_fu_69_ap_start <= grp_ntt_core_Pipeline_BUTTER_fu_69_ap_start_reg;
    icmp_ln24_fu_96_p2 <= "1" when (len_fu_54 = ap_const_lv8_0) else "0";
    icmp_ln27_fu_132_p2 <= "1" when (signed(tmp_fu_122_p4) < signed(ap_const_lv56_1)) else "0";
    k_1_fu_147_p2 <= std_logic_vector(unsigned(zext_ln21_reg_197) + unsigned(k_fu_50));
    len_1_fu_152_p4 <= len_fu_54(7 downto 1);
    mul_fu_106_p3 <= (len_fu_54 & ap_const_lv1_0);
    tmp_fu_122_p4 <= start_reg_58(63 downto 8);
    trunc_ln20_fu_138_p1 <= start_reg_58(8 - 1 downto 0);
    trunc_ln27_fu_114_p1 <= k_fu_50(8 - 1 downto 0);
    zbuf_address0 <= grp_ntt_core_Pipeline_BUTTER_fu_69_zbuf_address0;
    zbuf_ce0 <= grp_ntt_core_Pipeline_BUTTER_fu_69_zbuf_ce0;
    zext_ln21_fu_102_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(len_fu_54),11));
    zext_ln24_fu_161_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(len_1_fu_152_p4),8));
    zext_ln27_fu_118_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_fu_106_p3),64));
end behav;
