-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity top_ntt is
generic (
    C_M_AXI_GMEM_ADDR_WIDTH : INTEGER := 64;
    C_M_AXI_GMEM_ID_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_BUSER_WIDTH : INTEGER := 1;
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 6;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM_USER_VALUE : INTEGER := 0;
    C_M_AXI_GMEM_PROT_VALUE : INTEGER := 0;
    C_M_AXI_GMEM_CACHE_VALUE : INTEGER := 3 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    m_axi_gmem_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_AWREADY : IN STD_LOGIC;
    m_axi_gmem_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ADDR_WIDTH-1 downto 0);
    m_axi_gmem_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_AWUSER_WIDTH-1 downto 0);
    m_axi_gmem_WVALID : OUT STD_LOGIC;
    m_axi_gmem_WREADY : IN STD_LOGIC;
    m_axi_gmem_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH-1 downto 0);
    m_axi_gmem_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH/8-1 downto 0);
    m_axi_gmem_WLAST : OUT STD_LOGIC;
    m_axi_gmem_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_WUSER_WIDTH-1 downto 0);
    m_axi_gmem_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_ARREADY : IN STD_LOGIC;
    m_axi_gmem_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ADDR_WIDTH-1 downto 0);
    m_axi_gmem_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ARUSER_WIDTH-1 downto 0);
    m_axi_gmem_RVALID : IN STD_LOGIC;
    m_axi_gmem_RREADY : OUT STD_LOGIC;
    m_axi_gmem_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH-1 downto 0);
    m_axi_gmem_RLAST : IN STD_LOGIC;
    m_axi_gmem_RID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_RUSER_WIDTH-1 downto 0);
    m_axi_gmem_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BVALID : IN STD_LOGIC;
    m_axi_gmem_BREADY : OUT STD_LOGIC;
    m_axi_gmem_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_BUSER_WIDTH-1 downto 0);
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of top_ntt is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "top_ntt_top_ntt,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=17.036000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=15484,HLS_SYN_LUT=13184,HLS_VERSION=2025_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (11 downto 0) := "000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (11 downto 0) := "000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (11 downto 0) := "000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (11 downto 0) := "000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (11 downto 0) := "000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (11 downto 0) := "000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (11 downto 0) := "000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (11 downto 0) := "000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (11 downto 0) := "001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (11 downto 0) := "010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (11 downto 0) := "100000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant C_M_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv64_100 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000100000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal in_r : STD_LOGIC_VECTOR (63 downto 0);
    signal out_r : STD_LOGIC_VECTOR (63 downto 0);
    signal zetas_forward : STD_LOGIC_VECTOR (63 downto 0);
    signal buf_r_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal buf_r_ce0 : STD_LOGIC;
    signal buf_r_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal buf_r_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal buf_r_ce1 : STD_LOGIC;
    signal buf_r_we1 : STD_LOGIC;
    signal buf_r_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zbuf_ce0 : STD_LOGIC;
    signal zbuf_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal zbuf_ce1 : STD_LOGIC;
    signal zbuf_we1 : STD_LOGIC;
    signal gmem_blk_n_AW : STD_LOGIC;
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal gmem_blk_n_B : STD_LOGIC;
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal trunc_ln_reg_179 : STD_LOGIC_VECTOR (61 downto 0);
    signal trunc_ln65_1_reg_184 : STD_LOGIC_VECTOR (61 downto 0);
    signal trunc_ln1_reg_189 : STD_LOGIC_VECTOR (61 downto 0);
    signal grp_top_ntt_Pipeline_COPY_IN_fu_108_ap_start : STD_LOGIC;
    signal grp_top_ntt_Pipeline_COPY_IN_fu_108_ap_done : STD_LOGIC;
    signal grp_top_ntt_Pipeline_COPY_IN_fu_108_ap_idle : STD_LOGIC;
    signal grp_top_ntt_Pipeline_COPY_IN_fu_108_ap_ready : STD_LOGIC;
    signal grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_AWVALID : STD_LOGIC;
    signal grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_WVALID : STD_LOGIC;
    signal grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_WLAST : STD_LOGIC;
    signal grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_ARVALID : STD_LOGIC;
    signal grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_RREADY : STD_LOGIC;
    signal grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_BREADY : STD_LOGIC;
    signal grp_top_ntt_Pipeline_COPY_IN_fu_108_buf_r_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_top_ntt_Pipeline_COPY_IN_fu_108_buf_r_ce1 : STD_LOGIC;
    signal grp_top_ntt_Pipeline_COPY_IN_fu_108_buf_r_we1 : STD_LOGIC;
    signal grp_top_ntt_Pipeline_COPY_IN_fu_108_buf_r_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_top_ntt_Pipeline_COPY_IN_fu_108_zbuf_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_top_ntt_Pipeline_COPY_IN_fu_108_zbuf_ce1 : STD_LOGIC;
    signal grp_top_ntt_Pipeline_COPY_IN_fu_108_zbuf_we1 : STD_LOGIC;
    signal grp_top_ntt_Pipeline_COPY_IN_fu_108_zbuf_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_ntt_core_fu_120_ap_start : STD_LOGIC;
    signal grp_ntt_core_fu_120_ap_done : STD_LOGIC;
    signal grp_ntt_core_fu_120_ap_idle : STD_LOGIC;
    signal grp_ntt_core_fu_120_ap_ready : STD_LOGIC;
    signal grp_ntt_core_fu_120_buf_r_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_ntt_core_fu_120_buf_r_ce0 : STD_LOGIC;
    signal grp_ntt_core_fu_120_buf_r_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_ntt_core_fu_120_buf_r_ce1 : STD_LOGIC;
    signal grp_ntt_core_fu_120_buf_r_we1 : STD_LOGIC;
    signal grp_ntt_core_fu_120_buf_r_d1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_ntt_core_fu_120_zbuf_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_ntt_core_fu_120_zbuf_ce0 : STD_LOGIC;
    signal grp_top_ntt_Pipeline_COPY_OUT_fu_128_ap_start : STD_LOGIC;
    signal grp_top_ntt_Pipeline_COPY_OUT_fu_128_ap_done : STD_LOGIC;
    signal grp_top_ntt_Pipeline_COPY_OUT_fu_128_ap_idle : STD_LOGIC;
    signal grp_top_ntt_Pipeline_COPY_OUT_fu_128_ap_ready : STD_LOGIC;
    signal grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_AWVALID : STD_LOGIC;
    signal grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_WVALID : STD_LOGIC;
    signal grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_WLAST : STD_LOGIC;
    signal grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_ARVALID : STD_LOGIC;
    signal grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_RREADY : STD_LOGIC;
    signal grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_BREADY : STD_LOGIC;
    signal grp_top_ntt_Pipeline_COPY_OUT_fu_128_buf_r_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_top_ntt_Pipeline_COPY_OUT_fu_128_buf_r_ce0 : STD_LOGIC;
    signal gmem_0_AWVALID : STD_LOGIC;
    signal gmem_0_AWREADY : STD_LOGIC;
    signal gmem_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal gmem_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem_0_WVALID : STD_LOGIC;
    signal gmem_0_WREADY : STD_LOGIC;
    signal gmem_0_ARVALID : STD_LOGIC;
    signal gmem_0_ARREADY : STD_LOGIC;
    signal gmem_0_RVALID : STD_LOGIC;
    signal gmem_0_RREADY : STD_LOGIC;
    signal gmem_0_RDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem_0_RFIFONUM : STD_LOGIC_VECTOR (8 downto 0);
    signal gmem_0_BVALID : STD_LOGIC;
    signal gmem_0_BREADY : STD_LOGIC;
    signal grp_top_ntt_Pipeline_COPY_IN_fu_108_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_ntt_core_fu_120_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_top_ntt_Pipeline_COPY_OUT_fu_128_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal sext_ln74_fu_169_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component top_ntt_top_ntt_Pipeline_COPY_IN IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_gmem_0_AWVALID : OUT STD_LOGIC;
        m_axi_gmem_0_AWREADY : IN STD_LOGIC;
        m_axi_gmem_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_WVALID : OUT STD_LOGIC;
        m_axi_gmem_0_WREADY : IN STD_LOGIC;
        m_axi_gmem_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_WLAST : OUT STD_LOGIC;
        m_axi_gmem_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_ARVALID : OUT STD_LOGIC;
        m_axi_gmem_0_ARREADY : IN STD_LOGIC;
        m_axi_gmem_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_RVALID : IN STD_LOGIC;
        m_axi_gmem_0_RREADY : OUT STD_LOGIC;
        m_axi_gmem_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_0_RLAST : IN STD_LOGIC;
        m_axi_gmem_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_BVALID : IN STD_LOGIC;
        m_axi_gmem_0_BREADY : OUT STD_LOGIC;
        m_axi_gmem_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        sext_ln65 : IN STD_LOGIC_VECTOR (61 downto 0);
        sext_ln65_1 : IN STD_LOGIC_VECTOR (61 downto 0);
        buf_r_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        buf_r_ce1 : OUT STD_LOGIC;
        buf_r_we1 : OUT STD_LOGIC;
        buf_r_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        zbuf_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        zbuf_ce1 : OUT STD_LOGIC;
        zbuf_we1 : OUT STD_LOGIC;
        zbuf_d1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component top_ntt_ntt_core IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        buf_r_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        buf_r_ce0 : OUT STD_LOGIC;
        buf_r_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        buf_r_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        buf_r_ce1 : OUT STD_LOGIC;
        buf_r_we1 : OUT STD_LOGIC;
        buf_r_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        zbuf_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        zbuf_ce0 : OUT STD_LOGIC;
        zbuf_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component top_ntt_top_ntt_Pipeline_COPY_OUT IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_gmem_0_AWVALID : OUT STD_LOGIC;
        m_axi_gmem_0_AWREADY : IN STD_LOGIC;
        m_axi_gmem_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_WVALID : OUT STD_LOGIC;
        m_axi_gmem_0_WREADY : IN STD_LOGIC;
        m_axi_gmem_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_WLAST : OUT STD_LOGIC;
        m_axi_gmem_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_ARVALID : OUT STD_LOGIC;
        m_axi_gmem_0_ARREADY : IN STD_LOGIC;
        m_axi_gmem_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_RVALID : IN STD_LOGIC;
        m_axi_gmem_0_RREADY : OUT STD_LOGIC;
        m_axi_gmem_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_0_RLAST : IN STD_LOGIC;
        m_axi_gmem_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_BVALID : IN STD_LOGIC;
        m_axi_gmem_0_BREADY : OUT STD_LOGIC;
        m_axi_gmem_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        sext_ln74 : IN STD_LOGIC_VECTOR (61 downto 0);
        buf_r_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        buf_r_ce0 : OUT STD_LOGIC;
        buf_r_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component top_ntt_buf_r_RAM_2P_BRAM_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component top_ntt_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        in_r : OUT STD_LOGIC_VECTOR (63 downto 0);
        out_r : OUT STD_LOGIC_VECTOR (63 downto 0);
        zetas_forward : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component top_ntt_gmem_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_MAXREQS : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER;
        CH0_NUM_READ_OUTSTANDING : INTEGER;
        CH0_NUM_WRITE_OUTSTANDING : INTEGER;
        CH0_USER_RFIFONUM_WIDTH : INTEGER;
        CH0_USER_DW : INTEGER;
        CH0_USER_AW : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_CH0_ARVALID : IN STD_LOGIC;
        I_CH0_ARREADY : OUT STD_LOGIC;
        I_CH0_ARADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RVALID : OUT STD_LOGIC;
        I_CH0_RREADY : IN STD_LOGIC;
        I_CH0_RDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RFIFONUM : OUT STD_LOGIC_VECTOR (8 downto 0);
        I_CH0_AWVALID : IN STD_LOGIC;
        I_CH0_AWREADY : OUT STD_LOGIC;
        I_CH0_AWADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WVALID : IN STD_LOGIC;
        I_CH0_WREADY : OUT STD_LOGIC;
        I_CH0_WDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        I_CH0_BVALID : OUT STD_LOGIC;
        I_CH0_BREADY : IN STD_LOGIC );
    end component;



begin
    buf_r_U : component top_ntt_buf_r_RAM_2P_BRAM_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => buf_r_address0,
        ce0 => buf_r_ce0,
        q0 => buf_r_q0,
        address1 => buf_r_address1,
        ce1 => buf_r_ce1,
        we1 => buf_r_we1,
        d1 => buf_r_d1);

    zbuf_U : component top_ntt_buf_r_RAM_2P_BRAM_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 256,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => grp_ntt_core_fu_120_zbuf_address0,
        ce0 => zbuf_ce0,
        q0 => zbuf_q0,
        address1 => grp_top_ntt_Pipeline_COPY_IN_fu_108_zbuf_address1,
        ce1 => zbuf_ce1,
        we1 => zbuf_we1,
        d1 => grp_top_ntt_Pipeline_COPY_IN_fu_108_zbuf_d1);

    grp_top_ntt_Pipeline_COPY_IN_fu_108 : component top_ntt_top_ntt_Pipeline_COPY_IN
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_top_ntt_Pipeline_COPY_IN_fu_108_ap_start,
        ap_done => grp_top_ntt_Pipeline_COPY_IN_fu_108_ap_done,
        ap_idle => grp_top_ntt_Pipeline_COPY_IN_fu_108_ap_idle,
        ap_ready => grp_top_ntt_Pipeline_COPY_IN_fu_108_ap_ready,
        m_axi_gmem_0_AWVALID => grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_AWVALID,
        m_axi_gmem_0_AWREADY => ap_const_logic_0,
        m_axi_gmem_0_AWADDR => grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_AWADDR,
        m_axi_gmem_0_AWID => grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_AWID,
        m_axi_gmem_0_AWLEN => grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_AWLEN,
        m_axi_gmem_0_AWSIZE => grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_AWSIZE,
        m_axi_gmem_0_AWBURST => grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_AWBURST,
        m_axi_gmem_0_AWLOCK => grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_AWLOCK,
        m_axi_gmem_0_AWCACHE => grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_AWCACHE,
        m_axi_gmem_0_AWPROT => grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_AWPROT,
        m_axi_gmem_0_AWQOS => grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_AWQOS,
        m_axi_gmem_0_AWREGION => grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_AWREGION,
        m_axi_gmem_0_AWUSER => grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_AWUSER,
        m_axi_gmem_0_WVALID => grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_WVALID,
        m_axi_gmem_0_WREADY => ap_const_logic_0,
        m_axi_gmem_0_WDATA => grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_WDATA,
        m_axi_gmem_0_WSTRB => grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_WSTRB,
        m_axi_gmem_0_WLAST => grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_WLAST,
        m_axi_gmem_0_WID => grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_WID,
        m_axi_gmem_0_WUSER => grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_WUSER,
        m_axi_gmem_0_ARVALID => grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_ARVALID,
        m_axi_gmem_0_ARREADY => gmem_0_ARREADY,
        m_axi_gmem_0_ARADDR => grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_ARADDR,
        m_axi_gmem_0_ARID => grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_ARID,
        m_axi_gmem_0_ARLEN => grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_ARLEN,
        m_axi_gmem_0_ARSIZE => grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_ARSIZE,
        m_axi_gmem_0_ARBURST => grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_ARBURST,
        m_axi_gmem_0_ARLOCK => grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_ARLOCK,
        m_axi_gmem_0_ARCACHE => grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_ARCACHE,
        m_axi_gmem_0_ARPROT => grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_ARPROT,
        m_axi_gmem_0_ARQOS => grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_ARQOS,
        m_axi_gmem_0_ARREGION => grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_ARREGION,
        m_axi_gmem_0_ARUSER => grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_ARUSER,
        m_axi_gmem_0_RVALID => gmem_0_RVALID,
        m_axi_gmem_0_RREADY => grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_RREADY,
        m_axi_gmem_0_RDATA => gmem_0_RDATA,
        m_axi_gmem_0_RLAST => ap_const_logic_0,
        m_axi_gmem_0_RID => ap_const_lv1_0,
        m_axi_gmem_0_RFIFONUM => gmem_0_RFIFONUM,
        m_axi_gmem_0_RUSER => ap_const_lv1_0,
        m_axi_gmem_0_RRESP => ap_const_lv2_0,
        m_axi_gmem_0_BVALID => ap_const_logic_0,
        m_axi_gmem_0_BREADY => grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_BREADY,
        m_axi_gmem_0_BRESP => ap_const_lv2_0,
        m_axi_gmem_0_BID => ap_const_lv1_0,
        m_axi_gmem_0_BUSER => ap_const_lv1_0,
        sext_ln65 => trunc_ln_reg_179,
        sext_ln65_1 => trunc_ln65_1_reg_184,
        buf_r_address1 => grp_top_ntt_Pipeline_COPY_IN_fu_108_buf_r_address1,
        buf_r_ce1 => grp_top_ntt_Pipeline_COPY_IN_fu_108_buf_r_ce1,
        buf_r_we1 => grp_top_ntt_Pipeline_COPY_IN_fu_108_buf_r_we1,
        buf_r_d1 => grp_top_ntt_Pipeline_COPY_IN_fu_108_buf_r_d1,
        zbuf_address1 => grp_top_ntt_Pipeline_COPY_IN_fu_108_zbuf_address1,
        zbuf_ce1 => grp_top_ntt_Pipeline_COPY_IN_fu_108_zbuf_ce1,
        zbuf_we1 => grp_top_ntt_Pipeline_COPY_IN_fu_108_zbuf_we1,
        zbuf_d1 => grp_top_ntt_Pipeline_COPY_IN_fu_108_zbuf_d1);

    grp_ntt_core_fu_120 : component top_ntt_ntt_core
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_ntt_core_fu_120_ap_start,
        ap_done => grp_ntt_core_fu_120_ap_done,
        ap_idle => grp_ntt_core_fu_120_ap_idle,
        ap_ready => grp_ntt_core_fu_120_ap_ready,
        buf_r_address0 => grp_ntt_core_fu_120_buf_r_address0,
        buf_r_ce0 => grp_ntt_core_fu_120_buf_r_ce0,
        buf_r_q0 => buf_r_q0,
        buf_r_address1 => grp_ntt_core_fu_120_buf_r_address1,
        buf_r_ce1 => grp_ntt_core_fu_120_buf_r_ce1,
        buf_r_we1 => grp_ntt_core_fu_120_buf_r_we1,
        buf_r_d1 => grp_ntt_core_fu_120_buf_r_d1,
        zbuf_address0 => grp_ntt_core_fu_120_zbuf_address0,
        zbuf_ce0 => grp_ntt_core_fu_120_zbuf_ce0,
        zbuf_q0 => zbuf_q0);

    grp_top_ntt_Pipeline_COPY_OUT_fu_128 : component top_ntt_top_ntt_Pipeline_COPY_OUT
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_top_ntt_Pipeline_COPY_OUT_fu_128_ap_start,
        ap_done => grp_top_ntt_Pipeline_COPY_OUT_fu_128_ap_done,
        ap_idle => grp_top_ntt_Pipeline_COPY_OUT_fu_128_ap_idle,
        ap_ready => grp_top_ntt_Pipeline_COPY_OUT_fu_128_ap_ready,
        m_axi_gmem_0_AWVALID => grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_AWVALID,
        m_axi_gmem_0_AWREADY => gmem_0_AWREADY,
        m_axi_gmem_0_AWADDR => grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_AWADDR,
        m_axi_gmem_0_AWID => grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_AWID,
        m_axi_gmem_0_AWLEN => grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_AWLEN,
        m_axi_gmem_0_AWSIZE => grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_AWSIZE,
        m_axi_gmem_0_AWBURST => grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_AWBURST,
        m_axi_gmem_0_AWLOCK => grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_AWLOCK,
        m_axi_gmem_0_AWCACHE => grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_AWCACHE,
        m_axi_gmem_0_AWPROT => grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_AWPROT,
        m_axi_gmem_0_AWQOS => grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_AWQOS,
        m_axi_gmem_0_AWREGION => grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_AWREGION,
        m_axi_gmem_0_AWUSER => grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_AWUSER,
        m_axi_gmem_0_WVALID => grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_WVALID,
        m_axi_gmem_0_WREADY => gmem_0_WREADY,
        m_axi_gmem_0_WDATA => grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_WDATA,
        m_axi_gmem_0_WSTRB => grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_WSTRB,
        m_axi_gmem_0_WLAST => grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_WLAST,
        m_axi_gmem_0_WID => grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_WID,
        m_axi_gmem_0_WUSER => grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_WUSER,
        m_axi_gmem_0_ARVALID => grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_ARVALID,
        m_axi_gmem_0_ARREADY => ap_const_logic_0,
        m_axi_gmem_0_ARADDR => grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_ARADDR,
        m_axi_gmem_0_ARID => grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_ARID,
        m_axi_gmem_0_ARLEN => grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_ARLEN,
        m_axi_gmem_0_ARSIZE => grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_ARSIZE,
        m_axi_gmem_0_ARBURST => grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_ARBURST,
        m_axi_gmem_0_ARLOCK => grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_ARLOCK,
        m_axi_gmem_0_ARCACHE => grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_ARCACHE,
        m_axi_gmem_0_ARPROT => grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_ARPROT,
        m_axi_gmem_0_ARQOS => grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_ARQOS,
        m_axi_gmem_0_ARREGION => grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_ARREGION,
        m_axi_gmem_0_ARUSER => grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_ARUSER,
        m_axi_gmem_0_RVALID => ap_const_logic_0,
        m_axi_gmem_0_RREADY => grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_RREADY,
        m_axi_gmem_0_RDATA => ap_const_lv32_0,
        m_axi_gmem_0_RLAST => ap_const_logic_0,
        m_axi_gmem_0_RID => ap_const_lv1_0,
        m_axi_gmem_0_RFIFONUM => ap_const_lv9_0,
        m_axi_gmem_0_RUSER => ap_const_lv1_0,
        m_axi_gmem_0_RRESP => ap_const_lv2_0,
        m_axi_gmem_0_BVALID => gmem_0_BVALID,
        m_axi_gmem_0_BREADY => grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_BREADY,
        m_axi_gmem_0_BRESP => ap_const_lv2_0,
        m_axi_gmem_0_BID => ap_const_lv1_0,
        m_axi_gmem_0_BUSER => ap_const_lv1_0,
        sext_ln74 => trunc_ln1_reg_189,
        buf_r_address0 => grp_top_ntt_Pipeline_COPY_OUT_fu_128_buf_r_address0,
        buf_r_ce0 => grp_top_ntt_Pipeline_COPY_OUT_fu_128_buf_r_ce0,
        buf_r_q0 => buf_r_q0);

    control_s_axi_U : component top_ntt_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        in_r => in_r,
        out_r => out_r,
        zetas_forward => zetas_forward,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    gmem_m_axi_U : component top_ntt_gmem_m_axi
    generic map (
        CONSERVATIVE => 1,
        USER_MAXREQS => 7,
        MAX_READ_BURST_LENGTH => 16,
        MAX_WRITE_BURST_LENGTH => 16,
        C_M_AXI_ID_WIDTH => C_M_AXI_GMEM_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_GMEM_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_GMEM_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_GMEM_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_GMEM_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_GMEM_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_GMEM_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_GMEM_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_GMEM_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_GMEM_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_GMEM_CACHE_VALUE,
        CH0_NUM_READ_OUTSTANDING => 16,
        CH0_NUM_WRITE_OUTSTANDING => 16,
        CH0_USER_RFIFONUM_WIDTH => 9,
        CH0_USER_DW => 32,
        CH0_USER_AW => 64,
        NUM_READ_OUTSTANDING => 16,
        NUM_WRITE_OUTSTANDING => 16)
    port map (
        AWVALID => m_axi_gmem_AWVALID,
        AWREADY => m_axi_gmem_AWREADY,
        AWADDR => m_axi_gmem_AWADDR,
        AWID => m_axi_gmem_AWID,
        AWLEN => m_axi_gmem_AWLEN,
        AWSIZE => m_axi_gmem_AWSIZE,
        AWBURST => m_axi_gmem_AWBURST,
        AWLOCK => m_axi_gmem_AWLOCK,
        AWCACHE => m_axi_gmem_AWCACHE,
        AWPROT => m_axi_gmem_AWPROT,
        AWQOS => m_axi_gmem_AWQOS,
        AWREGION => m_axi_gmem_AWREGION,
        AWUSER => m_axi_gmem_AWUSER,
        WVALID => m_axi_gmem_WVALID,
        WREADY => m_axi_gmem_WREADY,
        WDATA => m_axi_gmem_WDATA,
        WSTRB => m_axi_gmem_WSTRB,
        WLAST => m_axi_gmem_WLAST,
        WID => m_axi_gmem_WID,
        WUSER => m_axi_gmem_WUSER,
        ARVALID => m_axi_gmem_ARVALID,
        ARREADY => m_axi_gmem_ARREADY,
        ARADDR => m_axi_gmem_ARADDR,
        ARID => m_axi_gmem_ARID,
        ARLEN => m_axi_gmem_ARLEN,
        ARSIZE => m_axi_gmem_ARSIZE,
        ARBURST => m_axi_gmem_ARBURST,
        ARLOCK => m_axi_gmem_ARLOCK,
        ARCACHE => m_axi_gmem_ARCACHE,
        ARPROT => m_axi_gmem_ARPROT,
        ARQOS => m_axi_gmem_ARQOS,
        ARREGION => m_axi_gmem_ARREGION,
        ARUSER => m_axi_gmem_ARUSER,
        RVALID => m_axi_gmem_RVALID,
        RREADY => m_axi_gmem_RREADY,
        RDATA => m_axi_gmem_RDATA,
        RLAST => m_axi_gmem_RLAST,
        RID => m_axi_gmem_RID,
        RUSER => m_axi_gmem_RUSER,
        RRESP => m_axi_gmem_RRESP,
        BVALID => m_axi_gmem_BVALID,
        BREADY => m_axi_gmem_BREADY,
        BRESP => m_axi_gmem_BRESP,
        BID => m_axi_gmem_BID,
        BUSER => m_axi_gmem_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_CH0_ARVALID => gmem_0_ARVALID,
        I_CH0_ARREADY => gmem_0_ARREADY,
        I_CH0_ARADDR => grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_ARADDR,
        I_CH0_ARLEN => grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_ARLEN,
        I_CH0_RVALID => gmem_0_RVALID,
        I_CH0_RREADY => gmem_0_RREADY,
        I_CH0_RDATA => gmem_0_RDATA,
        I_CH0_RFIFONUM => gmem_0_RFIFONUM,
        I_CH0_AWVALID => gmem_0_AWVALID,
        I_CH0_AWREADY => gmem_0_AWREADY,
        I_CH0_AWADDR => gmem_0_AWADDR,
        I_CH0_AWLEN => gmem_0_AWLEN,
        I_CH0_WVALID => gmem_0_WVALID,
        I_CH0_WREADY => gmem_0_WREADY,
        I_CH0_WDATA => grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_WDATA,
        I_CH0_WSTRB => grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_WSTRB,
        I_CH0_BVALID => gmem_0_BVALID,
        I_CH0_BREADY => gmem_0_BREADY);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_ntt_core_fu_120_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_ntt_core_fu_120_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_ntt_core_fu_120_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_ntt_core_fu_120_ap_ready = ap_const_logic_1)) then 
                    grp_ntt_core_fu_120_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_top_ntt_Pipeline_COPY_IN_fu_108_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_top_ntt_Pipeline_COPY_IN_fu_108_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_top_ntt_Pipeline_COPY_IN_fu_108_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_top_ntt_Pipeline_COPY_IN_fu_108_ap_ready = ap_const_logic_1)) then 
                    grp_top_ntt_Pipeline_COPY_IN_fu_108_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_top_ntt_Pipeline_COPY_OUT_fu_128_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_top_ntt_Pipeline_COPY_OUT_fu_128_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                    grp_top_ntt_Pipeline_COPY_OUT_fu_128_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_top_ntt_Pipeline_COPY_OUT_fu_128_ap_ready = ap_const_logic_1)) then 
                    grp_top_ntt_Pipeline_COPY_OUT_fu_128_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                trunc_ln1_reg_189 <= out_r(63 downto 2);
                trunc_ln65_1_reg_184 <= zetas_forward(63 downto 2);
                trunc_ln_reg_179 <= in_r(63 downto 2);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state5, ap_CS_fsm_state12, grp_top_ntt_Pipeline_COPY_IN_fu_108_ap_done, grp_ntt_core_fu_120_ap_done, grp_top_ntt_Pipeline_COPY_OUT_fu_128_ap_done, gmem_0_AWREADY, gmem_0_BVALID, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state7)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_top_ntt_Pipeline_COPY_IN_fu_108_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_ntt_core_fu_120_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((gmem_0_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if (((grp_top_ntt_Pipeline_COPY_OUT_fu_128_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                if (((gmem_0_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state12;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;

    ap_ST_fsm_state12_blk_assign_proc : process(gmem_0_BVALID)
    begin
        if ((gmem_0_BVALID = ap_const_logic_0)) then 
            ap_ST_fsm_state12_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state12_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_top_ntt_Pipeline_COPY_IN_fu_108_ap_done)
    begin
        if ((grp_top_ntt_Pipeline_COPY_IN_fu_108_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_ntt_core_fu_120_ap_done)
    begin
        if ((grp_ntt_core_fu_120_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state5_blk_assign_proc : process(gmem_0_AWREADY)
    begin
        if ((gmem_0_AWREADY = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_ST_fsm_state7_blk_assign_proc : process(grp_top_ntt_Pipeline_COPY_OUT_fu_128_ap_done)
    begin
        if ((grp_top_ntt_Pipeline_COPY_OUT_fu_128_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_CS_fsm_state12, gmem_0_BVALID)
    begin
        if (((gmem_0_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state12, gmem_0_BVALID)
    begin
        if (((gmem_0_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    buf_r_address0_assign_proc : process(grp_ntt_core_fu_120_buf_r_address0, grp_top_ntt_Pipeline_COPY_OUT_fu_128_buf_r_address0, ap_CS_fsm_state4, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            buf_r_address0 <= grp_top_ntt_Pipeline_COPY_OUT_fu_128_buf_r_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            buf_r_address0 <= grp_ntt_core_fu_120_buf_r_address0;
        else 
            buf_r_address0 <= "XXXXXXXX";
        end if; 
    end process;


    buf_r_address1_assign_proc : process(grp_top_ntt_Pipeline_COPY_IN_fu_108_buf_r_address1, grp_ntt_core_fu_120_buf_r_address1, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            buf_r_address1 <= grp_ntt_core_fu_120_buf_r_address1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            buf_r_address1 <= grp_top_ntt_Pipeline_COPY_IN_fu_108_buf_r_address1;
        else 
            buf_r_address1 <= "XXXXXXXX";
        end if; 
    end process;


    buf_r_ce0_assign_proc : process(grp_ntt_core_fu_120_buf_r_ce0, grp_top_ntt_Pipeline_COPY_OUT_fu_128_buf_r_ce0, ap_CS_fsm_state4, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            buf_r_ce0 <= grp_top_ntt_Pipeline_COPY_OUT_fu_128_buf_r_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            buf_r_ce0 <= grp_ntt_core_fu_120_buf_r_ce0;
        else 
            buf_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buf_r_ce1_assign_proc : process(grp_top_ntt_Pipeline_COPY_IN_fu_108_buf_r_ce1, grp_ntt_core_fu_120_buf_r_ce1, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            buf_r_ce1 <= grp_ntt_core_fu_120_buf_r_ce1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            buf_r_ce1 <= grp_top_ntt_Pipeline_COPY_IN_fu_108_buf_r_ce1;
        else 
            buf_r_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    buf_r_d1_assign_proc : process(grp_top_ntt_Pipeline_COPY_IN_fu_108_buf_r_d1, grp_ntt_core_fu_120_buf_r_d1, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            buf_r_d1 <= grp_ntt_core_fu_120_buf_r_d1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            buf_r_d1 <= grp_top_ntt_Pipeline_COPY_IN_fu_108_buf_r_d1;
        else 
            buf_r_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    buf_r_we1_assign_proc : process(grp_top_ntt_Pipeline_COPY_IN_fu_108_buf_r_we1, grp_ntt_core_fu_120_buf_r_we1, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            buf_r_we1 <= grp_ntt_core_fu_120_buf_r_we1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            buf_r_we1 <= grp_top_ntt_Pipeline_COPY_IN_fu_108_buf_r_we1;
        else 
            buf_r_we1 <= ap_const_logic_0;
        end if; 
    end process;


    gmem_0_ARVALID_assign_proc : process(ap_CS_fsm_state1, grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_ARVALID, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            gmem_0_ARVALID <= grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_ARVALID;
        else 
            gmem_0_ARVALID <= ap_const_logic_0;
        end if; 
    end process;


    gmem_0_AWADDR_assign_proc : process(ap_CS_fsm_state5, grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_AWADDR, gmem_0_AWREADY, ap_CS_fsm_state6, ap_CS_fsm_state7, sext_ln74_fu_169_p1)
    begin
        if (((gmem_0_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            gmem_0_AWADDR <= sext_ln74_fu_169_p1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            gmem_0_AWADDR <= grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_AWADDR;
        else 
            gmem_0_AWADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    gmem_0_AWLEN_assign_proc : process(ap_CS_fsm_state5, grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_AWLEN, gmem_0_AWREADY, ap_CS_fsm_state6, ap_CS_fsm_state7)
    begin
        if (((gmem_0_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            gmem_0_AWLEN <= ap_const_lv64_100(32 - 1 downto 0);
        elsif (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            gmem_0_AWLEN <= grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_AWLEN;
        else 
            gmem_0_AWLEN <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    gmem_0_AWVALID_assign_proc : process(ap_CS_fsm_state5, grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_AWVALID, gmem_0_AWREADY, ap_CS_fsm_state6, ap_CS_fsm_state7)
    begin
        if (((gmem_0_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            gmem_0_AWVALID <= ap_const_logic_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            gmem_0_AWVALID <= grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_AWVALID;
        else 
            gmem_0_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    gmem_0_BREADY_assign_proc : process(ap_CS_fsm_state12, grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_BREADY, gmem_0_BVALID, ap_CS_fsm_state6, ap_CS_fsm_state7)
    begin
        if (((gmem_0_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            gmem_0_BREADY <= ap_const_logic_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            gmem_0_BREADY <= grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_BREADY;
        else 
            gmem_0_BREADY <= ap_const_logic_0;
        end if; 
    end process;


    gmem_0_RREADY_assign_proc : process(ap_CS_fsm_state1, grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_RREADY, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            gmem_0_RREADY <= grp_top_ntt_Pipeline_COPY_IN_fu_108_m_axi_gmem_0_RREADY;
        else 
            gmem_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;


    gmem_0_WVALID_assign_proc : process(grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_WVALID, ap_CS_fsm_state6, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            gmem_0_WVALID <= grp_top_ntt_Pipeline_COPY_OUT_fu_128_m_axi_gmem_0_WVALID;
        else 
            gmem_0_WVALID <= ap_const_logic_0;
        end if; 
    end process;


    gmem_blk_n_AW_assign_proc : process(m_axi_gmem_AWREADY, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            gmem_blk_n_AW <= m_axi_gmem_AWREADY;
        else 
            gmem_blk_n_AW <= ap_const_logic_1;
        end if; 
    end process;


    gmem_blk_n_B_assign_proc : process(m_axi_gmem_BVALID, ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            gmem_blk_n_B <= m_axi_gmem_BVALID;
        else 
            gmem_blk_n_B <= ap_const_logic_1;
        end if; 
    end process;

    grp_ntt_core_fu_120_ap_start <= grp_ntt_core_fu_120_ap_start_reg;
    grp_top_ntt_Pipeline_COPY_IN_fu_108_ap_start <= grp_top_ntt_Pipeline_COPY_IN_fu_108_ap_start_reg;
    grp_top_ntt_Pipeline_COPY_OUT_fu_128_ap_start <= grp_top_ntt_Pipeline_COPY_OUT_fu_128_ap_start_reg;
        sext_ln74_fu_169_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1_reg_189),64));


    zbuf_ce0_assign_proc : process(grp_ntt_core_fu_120_zbuf_ce0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            zbuf_ce0 <= grp_ntt_core_fu_120_zbuf_ce0;
        else 
            zbuf_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    zbuf_ce1_assign_proc : process(grp_top_ntt_Pipeline_COPY_IN_fu_108_zbuf_ce1, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            zbuf_ce1 <= grp_top_ntt_Pipeline_COPY_IN_fu_108_zbuf_ce1;
        else 
            zbuf_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    zbuf_we1_assign_proc : process(grp_top_ntt_Pipeline_COPY_IN_fu_108_zbuf_we1, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            zbuf_we1 <= grp_top_ntt_Pipeline_COPY_IN_fu_108_zbuf_we1;
        else 
            zbuf_we1 <= ap_const_logic_0;
        end if; 
    end process;

end behav;
